### ISSUE TITLE
[Bug] Class 'Rinvex\\Testimonials\\Events\\AddressSaved' not found Laravel 6

### ISSUE THREAD

**Issue by mepoohsta** [rinvex/addresses#29] opened 2019-12-26 10:31 UTC
On $addressModel = $location->addresses()->firstOrCreate($address);

> {
>   "message": "Class 'Rinvex\\Testimonials\\Events\\AddressSaved' not found",
>   "exception": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
>   "file": "/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php",
>   "line": 205,
>   "trace": [
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php",
>       "line": 180,
>       "function": "fireCustomModelEvent",
>       "class": "Illuminate\\Database\\Eloquent\\Model",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php",
>       "line": 708,
>       "function": "fireModelEvent",
>       "class": "Illuminate\\Database\\Eloquent\\Model",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php",
>       "line": 679,
>       "function": "finishSave",
>       "class": "Illuminate\\Database\\Eloquent\\Model",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php",
>       "line": 281,
>       "function": "save",
>       "class": "Illuminate\\Database\\Eloquent\\Model",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Support/helpers.php",
>       "line": 422,
>       "function": "Illuminate\\Database\\Eloquent\\Relations\\{closure}",
>       "class": "Illuminate\\Database\\Eloquent\\Relations\\HasOneOrMany",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php",
>       "line": 282,
>       "function": "tap"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php",
>       "line": 220,
>       "function": "create",
>       "class": "Illuminate\\Database\\Eloquent\\Relations\\HasOneOrMany",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/app/Http/Controllers/Api/LocationController.php",
>       "line": 277,
>       "function": "firstOrCreate",
>       "class": "Illuminate\\Database\\Eloquent\\Relations\\HasOneOrMany",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php",
>       "line": 29,
>       "function": "App\\Http\\Controllers\\Api\\{closure}",
>       "class": "App\\Http\\Controllers\\Api\\LocationController",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php",
>       "line": 349,
>       "function": "transaction",
>       "class": "Illuminate\\Database\\Connection",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php",
>       "line": 261,
>       "function": "__call",
>       "class": "Illuminate\\Database\\DatabaseManager",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/app/Http/Controllers/Api/LocationController.php",
>       "line": 296,
>       "function": "__callStatic",
>       "class": "Illuminate\\Support\\Facades\\Facade",
>       "type": "::"
>     },
>     {
>       "function": "update",
>       "class": "App\\Http\\Controllers\\Api\\LocationController",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
>       "line": 54,
>       "function": "call_user_func_array"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
>       "line": 45,
>       "function": "callAction",
>       "class": "Illuminate\\Routing\\Controller",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
>       "line": 219,
>       "function": "dispatch",
>       "class": "Illuminate\\Routing\\ControllerDispatcher",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
>       "line": 176,
>       "function": "runController",
>       "class": "Illuminate\\Routing\\Route",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
>       "line": 681,
>       "function": "run",
>       "class": "Illuminate\\Routing\\Route",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
>       "line": 130,
>       "function": "Illuminate\\Routing\\{closure}",
>       "class": "Illuminate\\Routing\\Router",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authorize.php",
>       "line": 45,
>       "function": "Illuminate\\Pipeline\\{closure}",
>       "class": "Illuminate\\Pipeline\\Pipeline",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
>       "line": 171,
>       "function": "handle",
>       "class": "Illuminate\\Auth\\Middleware\\Authorize",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php",
>       "line": 41,
>       "function": "Illuminate\\Pipeline\\{closure}",
>       "class": "Illuminate\\Pipeline\\Pipeline",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
>       "line": 171,
>       "function": "handle",
>       "class": "Illuminate\\Routing\\Middleware\\SubstituteBindings",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php",
>       "line": 59,
>       "function": "Illuminate\\Pipeline\\{closure}",
>       "class": "Illuminate\\Pipeline\\Pipeline",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
>       "line": 171,
>       "function": "handle",
>       "class": "Illuminate\\Routing\\Middleware\\ThrottleRequests",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php",
>       "line": 43,
>       "function": "Illuminate\\Pipeline\\{closure}",
>       "class": "Illuminate\\Pipeline\\Pipeline",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
>       "line": 171,
>       "function": "handle",
>       "class": "Illuminate\\Auth\\Middleware\\Authenticate",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
>       "line": 105,
>       "function": "Illuminate\\Pipeline\\{closure}",
>       "class": "Illuminate\\Pipeline\\Pipeline",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
>       "line": 683,
>       "function": "then",
>       "class": "Illuminate\\Pipeline\\Pipeline",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
>       "line": 658,
>       "function": "runRouteWithinStack",
>       "class": "Illuminate\\Routing\\Router",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
>       "line": 624,
>       "function": "runRoute",
>       "class": "Illuminate\\Routing\\Router",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
>       "line": 613,
>       "function": "dispatchToRoute",
>       "class": "Illuminate\\Routing\\Router",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
>       "line": 170,
>       "function": "dispatch",
>       "class": "Illuminate\\Routing\\Router",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
>       "line": 130,
>       "function": "Illuminate\\Foundation\\Http\\{closure}",
>       "class": "Illuminate\\Foundation\\Http\\Kernel",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/barryvdh/laravel-cors/src/HandleCors.php",
>       "line": 36,
>       "function": "Illuminate\\Pipeline\\{closure}",
>       "class": "Illuminate\\Pipeline\\Pipeline",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
>       "line": 171,
>       "function": "handle",
>       "class": "Barryvdh\\Cors\\HandleCors",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
>       "line": 21,
>       "function": "Illuminate\\Pipeline\\{closure}",
>       "class": "Illuminate\\Pipeline\\Pipeline",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
>       "line": 171,
>       "function": "handle",
>       "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
>       "line": 21,
>       "function": "Illuminate\\Pipeline\\{closure}",
>       "class": "Illuminate\\Pipeline\\Pipeline",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
>       "line": 171,
>       "function": "handle",
>       "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",
>       "line": 27,
>       "function": "Illuminate\\Pipeline\\{closure}",
>       "class": "Illuminate\\Pipeline\\Pipeline",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
>       "line": 171,
>       "function": "handle",
>       "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php",
>       "line": 62,
>       "function": "Illuminate\\Pipeline\\{closure}",
>       "class": "Illuminate\\Pipeline\\Pipeline",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
>       "line": 171,
>       "function": "handle",
>       "class": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/fideloper/proxy/src/TrustProxies.php",
>       "line": 57,
>       "function": "Illuminate\\Pipeline\\{closure}",
>       "class": "Illuminate\\Pipeline\\Pipeline",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
>       "line": 171,
>       "function": "handle",
>       "class": "Fideloper\\Proxy\\TrustProxies",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/hyn/multi-tenant/src/Middleware/EagerIdentification.php",
>       "line": 29,
>       "function": "Illuminate\\Pipeline\\{closure}",
>       "class": "Illuminate\\Pipeline\\Pipeline",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
>       "line": 171,
>       "function": "handle",
>       "class": "Hyn\\Tenancy\\Middleware\\EagerIdentification",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/hyn/multi-tenant/src/Middleware/HostnameActions.php",
>       "line": 75,
>       "function": "Illuminate\\Pipeline\\{closure}",
>       "class": "Illuminate\\Pipeline\\Pipeline",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
>       "line": 171,
>       "function": "handle",
>       "class": "Hyn\\Tenancy\\Middleware\\HostnameActions",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
>       "line": 105,
>       "function": "Illuminate\\Pipeline\\{closure}",
>       "class": "Illuminate\\Pipeline\\Pipeline",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
>       "line": 145,
>       "function": "then",
>       "class": "Illuminate\\Pipeline\\Pipeline",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
>       "line": 110,
>       "function": "sendRequestThroughRouter",
>       "class": "Illuminate\\Foundation\\Http\\Kernel",
>       "type": "->"
>     },
>     {
>       "file": "/var/www/public/index.php",
>       "line": 55,
>       "function": "handle",
>       "class": "Illuminate\\Foundation\\Http\\Kernel",
>       "type": "->"
>     }
>   ]
> }

**Comment by rjp2525** [comment] 2020-01-10 19:03
Not sure why it's under a different namespace in the same package.. Same error.

**Comment by alvahamit** [comment] 2020-02-12 13:40
Having same issue. I am using Laravel 6.

**Comment by adrianmejias** [comment] 2020-02-17 09:44
I believe this is missing a required package within the composer.json file.

[Laravel Testimonials](https://github.com/rinvex/laravel-testimonials)

An option until the Laravel Addresses package is updated would be to install the package separately.

**Comment by yuriybabenko** [comment] 2020-03-10 19:36
Also running into the same issue.

**Comment by SimonErich** [comment] 2020-06-01 08:01
Is there a stable repo with this issue fixed or could you please merge this?

**Comment by goshku** [comment] 2020-06-06 20:37
Laravel 7 - still the problem is presents.
#30 - is fixing the problem :) 

Merge 🥇

**Comment by Omranic** [comment] 2020-06-07 04:50
This is now fixed in #30

**Closed as completed by Omranic** 2020-06-07 04:50 UTC

**Comment by blwsh** [comment] 2020-07-06 17:03
Anybody else still getting this issue on L6?
